[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "idealista18-anomalies"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.32.2,<2",
    "plotly>=5,<6"
]

[tool.setuptools.packages.find]
where = ["src"]
